// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjviioqjeawekgydihns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdmlpb3FqZWF3ZWtneWRpaG5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Mzc0MjIsImV4cCI6MjA2MzIxMzQyMn0.TVuYqD85sPppkIfAV5YELFF9cFkB2qk--uknPRtOl2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);